version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXTAUTH_SECRET: "09b8e43822d4367ec599fed1c2806fb75488209f8ee11d254fdeff8a90ce0a0a"
      NEXTAUTH_URL: "http://localhost:3000"
      DATABASE_URL: "mysql://Fatoumata:1234@db:3306/association"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: association
      MYSQL_USER: Fatoumata
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./association.sql:/docker-entrypoint-initdb.d/association.sql 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: Fatoumata
      PMA_PASSWORD: 1234
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
